
pipeline {
  environment {
    no_proxy     = ".dgfip,.impots,.rie.gouv.fr,100.67.225.0/24"
    http_proxy   = "http://10.154.68.7:8080"
    https_proxy  = "http://10.154.68.7:8080"
    project      = "PHPConfigTree"
    scannerHome  = tool 'sonar-scanner'
    XDEBUG_MODE  = "coverage"
  }
  agent  { label 'rocky8' }
  stages {
    stage('build and test') {
      matrix {
        axes {
          axis {
            name 'IMAGE'
            values 'php74','php81'
          }
          axis {
            name 'PREFERED_PACKAGES'
            values 'stable','lowest'
          }
        }
        agent {
          docker {
            image '$IMAGE'
            reuseNode true
          }
        }
        stages {
          stage('Build and test') {
            options {
              lock( "synchronous-matrix" )
            }
            steps {
              sh "composer update --prefer-$PREFERED_PACKAGES --prefer-dist --no-interaction"
              script {
                if ( env.PREFERED_PACKAGES == "stable" ) {
                  catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                      sh 'composer run phpcs' 
                  }
                  catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    def result = sh(returnStdout: true, script: 'composer run phpstan')
                    writeFile(file: "tests/results/phpstan.xml", text: result)
                    sh "cat tests/results/phpstan.xml"
                  }
                }
              }
              catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                script {
                  if ( env.PREFERED_PACKAGES == "stable" ) {
                    def result = sh(returnStdout: true, script: 'composer run phpstan')
                    writeFile(file: "tests/results/phpstan.xml", text: result)
                    sh "cat tests/results/phpstan.xml"
                  } else {
                    sh 'rm -f tests/results/phpstan.xml'
                  }
                }
              }
              catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                  sh 'composer run test'
              }
              junit testResults: 'tests/results/*.xml', skipPublishingChecks: true, allowEmptyResults: true
              sh "ls tests/results"
              stash name: "test_${IMAGE}_${PREFERED_PACKAGES}"
            }
          }
        }
      }
    }
    stage('sonarQube') {
      steps {
        unstash name: 'test_php81_stable'
        script {
          projectKey        = "-Dsonar.projectKey=${project}"
          sources           = "-Dsonar.sources=${workspace}/src"
          testReports       = "-Dsonar.php.tests.reportPath=${workspace}/tests/results/*.xml"
          coverage          = "-Dsonar.php.coverage.reportPaths=${workspace}/tests/results/coverage.xml"
          withSonarQubeEnv('Sonarqube-server') {
              sh "${scannerHome}/bin/sonar-scanner ${projectKey} -Dsonar.tests=${workspace}/tests ${sources} ${testReports} ${coverage}"
          }
        }
      }
    }
  }
}